server.port=1515

spring.application.name=carcosa

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.com.home.carcosa.boardgame=DEBUG
logging.level.org.springframework=INFO