package com.home.carcosa.service;

import java.util.List;

import org.springframework.stereotype.Service;

import com.home.carcosa.dto.JokeResponse;

@Service
public class JokeService {

    public static final List<String> JOKES = List.of(
            "I told my computer I needed a break, and it said: no problem—I'll go to sleep.",
            "I tried to catch fog yesterday; I mist.",
            "I'm reading a book on anti-gravity—it's impossible to put down.",
            "My calendar's days are numbered.", "I used to be indecisive; now I'm not so sure.",
            "I asked the librarian if the library had books on paranoia; she whispered, 'They're right behind you.'",
            "I bought a pencil that used to belong to Shakespeare—now I chew it a lot.",
            "I don't trust stairs; they're always up to something.",
            "I told a joke about a roof once—went over everyone's head.",
            "I would tell you a construction joke, but I'm still working on it.",
            "I'm on a seafood diet—I see food and I eat it.",
            "I tried to make a belt out of watches—what a waist of time.",
            "I got fired from the keyboard factory; I didn't put in enough shifts.",
            "My phone battery and I have a lot in common—we both drain fast.",
            "I named my dog 'Five Miles' so I can say I walk Five Miles every day.",
            "I accidentally swallowed some food coloring; the doctor says I'm OK but I feel like I've dyed a little inside.",
            "I used to hate facial hair, but then it grew on me.",
            "I wanted to learn how to drive a stick shift, but I couldn't find the manual.",
            "I made a pun about the wind, but it blows.", "I told my plants a joke; now they're in stitches.",
            "I stayed up all night wondering where the sun went—then it dawned on me.",
            "My friend said I'm condescending; that means I talk down to people.",
            "I have a joke about paper—it's tearable.",
            "I tried to organize a hide-and-seek tournament, but good players are hard to find.",
            "I would tell a time-travel joke, but you didn't like it.",
            "I tried to take a photo of the sun, but it was too bright—so I used a shade.",
            "I asked my coffee if it was ready; it said, 'Espresso-ly.'",
            "I tried to write a joke about pizza, but it was too cheesy.",
            "I'm terrified of elevators, so I'm taking steps to avoid them.",
            "I gave my handyman a to-do list; he said it was riveting.",
            "I told my suitcase there'd be no vacation this year—now it's dealing with emotional baggage.",
            "I don't play soccer because I enjoy it; I'm just doing it for kicks.",
            "My math teacher called me average—how mean.", "I have a joke about a broken pencil—pointless.",
            "I used to be a baker, but I couldn't make enough dough.",
            "I'm friends with all the letters of the alphabet; we're on good terms.",
            "I got a job at a bakery because I kneaded it.", "I asked the mirror for advice; it said, 'Reflect on it.'",
            "I tried to make a joke about glue, but I couldn't stick the landing.",
            "I'm writing a book about mountains; it's a cliffhanger.",
            "I bought a ceiling fan yesterday; complete waste—I can't stop staring up.",
            "I once had a fear of hurdles, but I got over it.", "I told a joke about a boomerang; it came back to me.",
            "I ordered a chicken and an egg online; I'll let you know which arrives first.",
            "My vacuum is so moody; it really sucks.", "I wanted to be a doctor, but I didn't have the patients.",
            "I tried to start a hot air balloon business, but it never took off.",
            "I got a new job drilling holes; it's boring, but it pays.",
            "I told my boss three company jokes; sadly, none of them worked.",
            "I'm learning sign language; it's very handy.", "I used to be addicted to soap, but I'm clean now.",
            "I told a joke about a stopwatch; it was time-consuming.",
            "I bought shoes from a magician; I don't know what he laced them with, but I kept disappearing.",
            "I'm great at multitasking: I can waste time, be unproductive, and procrastinate all at once.",
            "I tried to make a pun about the ocean, but it was too deep.",
            "I can't believe I got fired from the orange juice factory; I just couldn't concentrate.",
            "I asked my dog what's two minus two; he said nothing.", "I'm not lazy; I'm on energy-saving mode.",
            "I'm writing a song about a tortilla; it's a wrap.",
            "I have a joke about chemistry, but I'm not sure it will get a reaction.",
            "I tried to start a gardening club, but it didn't grow on anyone.",
            "I'd tell you a joke about electricity, but it's shocking.",
            "I broke my finger last week; on the other hand, I'm OK.",
            "I asked the banker to check my balance; she pushed me.",
            "I tried to paint with invisible ink; the results were hard to see.",
            "I'm reading a book about teleportation; it's bound to take me places.",
            "I got a job at a clock factory; it's about time.", "I used to be a banker, but I lost interest.",
            "I bought a notebook that's allergic to math; it breaks out in problems.",
            "I have a joke about knitting; it's a bit tangled.",
            "I tried to be a chef, but I couldn't handle the pressure cooker.",
            "My playlist is like my fridge: mostly leftovers.",
            "I tried to tell a joke about bread, but it was too crumby.",
            "I was going to tell a joke about procrastination, but I'll do it later.",
            "I asked my GPS for a joke; it said, 'Recalculating.'",
            "I told my therapist I feel invisible; he said, 'Who said that?'",
            "I was going to tell a joke about UDP, but you might not get it.",
            "I told a TCP joke once; it was acknowledged.",
            "I'm not afraid of commitment; I'm afraid of meetings that could've been emails.",
            "I tried to make a joke about HTML, but it didn't have the right tag.",
            "I have a joke about Java, but it might take a while to brew.",
            "I asked the IT guy for a joke; he said, 'Have you tried turning it off and on again?'",
            "I tried to debug my life, but I couldn't reproduce the issue.",
            "I renamed my iPod 'Titanic'; now it's syncing.", "My Wi‑Fi and I are in a relationship; it's complicated.",
            "I made a joke about cloud storage, but it went over my head.", "I told my computer a joke; it crashed.",
            "I'm writing a book about batteries; it has a lot of energy.",
            "I tried to use a USB as a joke; it never goes in the right way the first time.",
            "I opened a bakery for programmers; we only sell byte-sized snacks.",
            "I tried to make a joke about recursion, but I tried to make a joke about recursion.",
            "My code and I have trust issues; it works on my machine.",
            "I got a new keyboard; it's got great character.", "I told a joke about a pointer; it was right on.",
            "I tried to catch some HTTP errors, but they kept getting away—404 of them.",
            "I asked my database for a joke; it said, 'SELECT one you like.'",
            "I tried to tell a Git joke, but I couldn't commit.", "I made a joke about DNS; it had a great resolution.",
            "I told a joke about containers; it was dock-umented.",
            "I tried to tell a joke about Kubernetes; it didn't scale.", "I asked the ocean for directions; it waved.",
            "I told my wall a joke; it cracked up.",
            "I tried to take the stairs to success, but I tripped on the first step.",
            "I have a joke about a pencil sharpener; it's on point.",
            "I told a joke about a blanket; it had me covered.",
            "I tried to start a band called 1023MB; we never got a gig.",
            "I asked the tree for advice; it said, 'Leaf it alone.'",
            "I tried to make a joke about a broken chair, but it couldn't stand up.",
            "I wrote a joke about a treadmill; it's running in place.", "I told my watch a joke; it ticked me off.",
            "I have a joke about a mailbox; it delivers.",
            "I tried to write a joke about a fence; it was over the line.",
            "I told my shoes a joke; they were laced with laughter.",
            "I asked my sandwich if it wanted to hear a joke; it said, 'Lettuce begin.'",
            "I told a joke about a fork; it had a good point.",
            "I tried to make a joke about a candle, but it burned out.",
            "I told a joke about a mirror; it was a good reflection.",
            "I tried to make a joke about a hammer; it hit the nail on the head.",
            "I told a joke about a map; it had a lot of points.", "I asked my pen for help; it drew a blank.",
            "I told a joke about a door; it was unhinged.", "I tried to tell a joke about a banana, but I slipped up.",
            "I told my refrigerator a joke; it couldn't stop chilling.",
            "I tried to make a joke about a magnet; it was very attractive.",
            "I told a joke about a sponge; it soaked it up.",
            "I asked the moon for a joke; it said it was over the crater.",
            "I tried to make a joke about a dictionary, but I couldn't find the words.",
            "I told a joke about a clock; it was timely.", "I asked my notebook for jokes; it had a lot of lines.",
            "I tried to make a joke about an elevator; it had its ups and downs.",
            "I told a joke about a screwdriver; it really turned things around.",
            "I asked my thermostat for a joke; it said, 'Cool story.'",
            "I tried to tell a joke about a printer; it just jammed.", "I told a joke about a window; it was pane-ful.",
            "I asked the river for a joke; it said, 'Go with the flow.'",
            "I tried to tell a joke about a camera; it didn't focus.",
            "I told a joke about a broom; it swept the room.",
            "I asked the sun for a joke; it said, 'You wouldn't get it—it's a bit radiant.'",
            "I tried to tell a joke about a notebook; it was sketchy.",
            "I told a joke about a flashlight; it brightened my day.",
            "I asked my kettle for a joke; it said, 'I'm boiling with ideas.'",
            "I tried to tell a joke about a shoe; it was a little sole-less.",
            "I told a joke about a ladder; it rose to the occasion.",
            "I asked my pizza for a joke; it said, 'Slice to meet you.'",
            "I tried to make a joke about a snowman; it was cool.",
            "I told a joke about a tree; it was rooted in truth.",
            "I asked my alarm clock for a joke; it said, 'Time to wake up to reality.'",
            "I tried to tell a joke about a unicycle; it was one-wheeled.",
            "I told a joke about a mushroom; it was a fun guy.",
            "I tried to tell a joke about a scarf, but it was a bit of a wrap.");

    public JokeResponse getJoke() {
        return new JokeResponse(JOKES.get((int) (Math.random() * JOKES.size())));
    }
}
