services:
  oracle-xe:
    image: tomdenem1010/carcosa-db:latest
    pull_policy: always
    container_name: carcosa-oracle-xe
    ports:
      - "1521:1521"  # Oracle listener
      - "5500:5500"  # EM Express
    env_file:
      - .env
    volumes:
      - ./oradata:/opt/oracle/oradata
