services:
  oracle-xe:
    build:
      context: .
      dockerfile: Dockerfile
    image: carcosa-oracle-xe:21
    container_name: carcosa-oracle-xe
    ports:
      - "1521:1521"  # Oracle listener
      - "5500:5500"  # EM Express
    env_file:
      - .env
    volumes:
      - ./oradata:/opt/oracle/oradata
