apiVersion: v1
kind: Service
metadata:
    name: carcosa
    annotations:
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
        service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-0ecb92c7f77bcde5d,subnet-0166cbe7bf8dba2ef
spec:
    selector:
        app: carcosa
    type: LoadBalancer
    ports:
        -   protocol: TCP
            port: 80
            targetPort: 1895
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: carcosa
spec:
    replicas: 2
    selector:
        matchLabels:
            app: carcosa
    template:
        metadata:
            labels:
                app: carcosa
        spec:
            containers:
                - name: carcosa
                  image: tomdenem1010/carcosa:IMAGE_TAG
                  ports:
                      - containerPort: 1895