CREATE TABLE BOARDGAME (
  	ID NUMBER PRIMARY KEY,
  	NAME VARCHAR2(255) NOT NULL,
  	TYPE VARCHAR2(255) NOT NULL,
  	STATUS VARCHAR2(255) NOT NULL,
  	BGG_LINK VARCHAR2(255) NOT NULL,
  	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  	UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  	UNIQUE (BGG_LINK),
  	CONSTRAINT CHECK_BOARDGAME_TYPE CHECK (TYPE IN ('BASEGAME', 'EXPANSION')),
	CONSTRAINT CHECK_BOARDGAME_STATUS CHECK (STATUS IN ('OWN', 'SOLD', 'THINKINGTOSELL', 'THINKINGTOBUY'))
);

CREATE INDEX INDEX_BOARDGAME_NAME ON BOARDGAME (NAME);
CREATE INDEX INDEX_BOARDGAME_STATUS ON BOARDGAME (STATUS);

CREATE SEQUENCE BOARDGAME_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;





CREATE TABLE BOARDGAME_GROUP (
  ID NUMBER PRIMARY KEY,
  GROUP_ID NUMBER NOT NULL,
  BOARDGAME_ID NUMBER NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY (BOARDGAME_ID) REFERENCES BOARDGAME(ID),
  UNIQUE (BOARDGAME_ID)
);

CREATE INDEX INDEX_BOARDGAME_GROUP_GROUP_ID ON BOARDGAME_GROUP (GROUP_ID);

CREATE SEQUENCE BOARDGAME_GROUP_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;





CREATE TABLE BOARDGAME_PLAY (
  ID NUMBER PRIMARY KEY,
  BOARDGAME_ID NUMBER NOT NULL,
  PLAY_DATE DATE NOT NULL,
  PLAYER_COUNT NUMBER NOT NULL,
  WIN VARCHAR2(255) NOT NULL,
  FUN_SCORE NUMBER NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY (BOARDGAME_ID) REFERENCES BOARDGAME(ID),
  CONSTRAINT CHECK_BOARDGAME_PLAY_WIN CHECK (WIN IN ('SUCCESS', 'FAILURE')),
  CONSTRAINT CHECK_BOARDGAME_PLAY_FUN_SCORE CHECK (FUN_SCORE >= 1 AND FUN_SCORE <= 5)
);

CREATE SEQUENCE BOARDGAME_PLAY_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
